
#define MODEL_NUMBER_L 0x00
#define MODOEL_NUMBER_H 0x01
#define VERSION 0x02
#define ID 0x03
#define BAUD_RATE 0x04
#define RETURN_DELAY_TIME 0x05
#define CW_ANGLE_LIMIT_L 0x06
#define CW_ANGLE_LIMIT_H 0x07
#define CCW_ANGLE_LIMIT_L 0x08
#define CCW_ANGLE_LIMIT_H 0x09
#define SYSTEM_DATA2 0x0A
#define LIMIT_TEMPERATURE 0x0B
#define DOWN_LIMIT_VOLTAGE 0x0C
#define UP_LIMIT_VOLTAGE 0x0D
#define MAX_TORQUE_L 0x0E
#define MAX_TORQUE_H 0x0F
#define RETURN_LEVEL 0x10
#define ALARM_LED 0x11
#define ALARM_SHUTDOWN 0x12
#define OPERATING_MODE 0x13
#define DOWN_CALIBRATION_L 0x14
#define DOWN_CALIBRATION_H 0x15
#define UP_CALIBRATION_L 0x16
#define UP_CALIBRATION_H 0x17
#define TORQUE_ENABLE 0x18
#define LED 0x19
#define CW_COMPLIANCE_MARGIN 0x1A
#define CCW_COMPLIANCE_MARGIN 0x1B
#define CW_COMPLIANCE_SLOPE 0x1C
#define CCW_COMPLIANCE_SLOPE 0x1D
#define GOAL_POSITION_L 0x1E
#define GOAL_POSITION_H 0x1F
#define GOAL_SPEED_L 0x20
#define GOAL_SPEED_H 0x21
#define TORQUE_LIMIT_L 0x22
#define TORQUE_LIMIT_H 0x23
#define PRESENT_POSITION_L 0x24
#define PRESENT_POSITION_H 0x25
#define PRESENT_SPEED_L 0x26
#define PRESENT_SPEED_H 0x27
#define PRESENT_LOAD_L 0x28
#define PRESENT_LOAD_H 0x29
#define PRESENT_VOLTAGE 0x2A
#define PRESENT_TEMPERATURE 0x2B
#define REGISTERED_INSTRUCTION 0x2C
#define PAUSE_TIME 0x2D
#define MOVING 0x2E
#define LOCK 0x2F
#define PUNCH_L 0x30
#define PUNCH_H 0x31

#define STARTER_PACKAGE 0xFFFF
#define DEFAULT_BAUD 115200 

#define PING (0x01)
#define READ_DATA (0x02)
#define WRITE_DATA (0x03)
#define REG_WRITE (0x04)
#define ACTION (0x05)
#define RESET (0x06)
#define SYNC_WRITE (0x83)

#define LOW_MASK 0b0000000011111111
#define HIGH_MASK ~LOW_MASK
#define NORMAL_SPEED_LOW 0x00
#define NORMAL_SPEED_HIGH 0x02

#define DEFAULT_RX (PinName) PE_7
#define DEFAULT_TX (PinName) PE_8

#define BROADCAST_ID 0xFE
#define TEMP_MAX 0xFF
#define VOLT_L 0x5A
#define VOLT_H 0x8C
#define TORQUE_L 0xFF
#define TORQUE_H 0x03
#define RETURN_STATUS 0x01
#define LED_BLINK 0x20
#define SHUTDOWN 0x00